"""Add time_added_sec to ActiveExamSession

Revision ID: 5fe8547c6e09
Revises: 
Create Date: 2025-10-17 00:12:10.040707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe8547c6e09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_exam_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_added_sec', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_exam_session', schema=None) as batch_op:
        batch_op.drop_column('time_added_sec')

    # ### end Alembic commands ###
